### ISSUE TITLE
errors on cloned repo from dev branch(frontend dev branch)

### ISSUE THREAD

**Issue by kilik42** [urbanarray/UA-Frontend#42]
the solution for (if you only download the dev branch) if you get the error:
react-boilerplate@3.5.0 start /Users/yourname/yourlocation/UA-Frontend-development
> cross-env NODE_ENV=development node server

sh: cross-env: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT

npm ERR! syscall spawn
npm ERR! react-boilerplate@3.5.0 start: `cross-env NODE_ENV=development node server`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the react-boilerplate@3.5.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

solution:  you should run npm install cross-env
then npm install then npm run start
should probably be in the git for if this error occurs sh: cross-env: command not found

**Comment by mmarovich** [comment]
@kilik42 It doesn't sound like this is an issue that can be re-created with a proper fork, clone, and yarn or npm install.  If that doesn't sound right, please give us a detailed description of the steps that you took to re-create this particular error, with specifics on how our code was copied on your computer.
